# Create the bcbio_vm docker image on AWS, uploading to S3
---
- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Launch instance
      local_action:
        module: ec2
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        volumes:
          - device_name: /dev/sda1
            volume_size: 15
            delete_on_termination: true
        wait: true
      register: ec2

    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=15 timeout=320 state=started
      with_items: ec2.instances

    - name: Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
      shell: ssh-keyscan {{ item.public_ip }} >> $HOME/.ssh/known_hosts
      with_items: ec2.instances

- name: Rebuild and update bcbio_vm docker instance on S3
  hosts: launched
  connection: paramiko
  gather_facts: True
  vars:
    bcbio_dir: /tmp/bcbio-nextgen
  roles:
    - docker
    - gof3r
    - bcbio_vm_build

- name: Terminate EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Terminate instances that were previously launched
      local_action:
        module: ec2
        state: 'absent'
        region: '{{ region }}'
        instance_ids: '{{ ec2.instance_ids }}'